defaults:
  local: ../base.yaml

name:                simple-api
version:             0.1.0
license:             MIT
author:              MATSUBARA Nobutada
maintainer:          t12307043@gunma-u.ac.jp
copyright:           MATSUBARA Nobutada

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- aeson
- http-api-data
- req >= 2.0.0
- text

library:
  source-dirs: src
