name: Verify

on:
  pull_request: null
  push:
    branches:
    - master

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019]
        ghc: ["8.8.3"]

    steps:
    - uses: actions/checkout@v2

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v1.1.2
      with:
        path: ~/.stack
        key: "\
          ${{ runner.os }}-stack\
          -${{ hashFiles('**/extensible-http-api-data.cabal') }}\
          -${{ hashFiles('**/simple-api.cabal') }}\
        "
        restore-keys: |
          ${{ runner.os }}-stack-

    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
    - uses: matsubara0507/setup-stack@master
    - name: Remove GHC in .stack
      run: rm -rfd ~/.stack/programs

    - name: Install dependencies
      run: stack --system-ghc test --only-dependencies

    - name: Run test
      run: stack --system-ghc test
